# Generated by Django 2.1.7 on 2019-04-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190413_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Programs.Program'),
        ),
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.University'),
        ),
    ]
