# Generated by Django 2.1.7 on 2019-04-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190414_1129'),
        ('applications', '0003_auto_20190414_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='studentName',
        ),
        migrations.AddField(
            model_name='application',
            name='studentInfo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.StudentInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='studentProf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.UserProfile'),
            preserve_default=False,
        ),
    ]
