# Generated by Django 2.1.7 on 2019-04-12 15:09

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, default='', max_length=200)),
                ('nationalID', models.CharField(blank=True, default='', max_length=200)),
                ('DateOfBirth', models.DateField(blank=True, default=datetime.date(2019, 4, 12))),
                ('gender', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zipcode', models.IntegerField(blank=True, default=0)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=0, max_length=128, unique=True)),
                ('previousSchool', models.CharField(blank=True, default='', max_length=200)),
                ('highest_level_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('year_of_completion', models.DateField(blank=True, default=datetime.date(2019, 4, 12))),
                ('certificate_of_study', models.FileField(blank=True, upload_to=accounts.models.user_path)),
                ('transcript', models.FileField(blank=True, upload_to=accounts.models.user_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('university', models.CharField(blank=True, default='', max_length=50)),
                ('profilePic', models.ImageField(blank=True, upload_to=accounts.models.user_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
