# Generated by Django 2.1.7 on 2019-04-12 17:39

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='DateOfBirth',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 13)),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='year_of_completion',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 13)),
        ),
    ]
