# Generated by Django 2.1.7 on 2019-04-14 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190413_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='DateOfBirth',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 14)),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='year_of_completion',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 14)),
        ),
    ]
