# Generated by Django 2.1.7 on 2019-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='phone_number',
            field=models.IntegerField(max_length=200),
        ),
    ]
