# Generated by Django 2.1.7 on 2019-03-21 14:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20190321_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, unique=True),
        ),
    ]
