# Generated by Django 2.1.7 on 2019-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20190321_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='photo_main',
            field=models.ImageField(default='', upload_to='photos/%title'),
            preserve_default=False,
        ),
    ]
