# Generated by Django 2.1.7 on 2019-03-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_university_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='photo_main',
            field=models.ImageField(upload_to='UniPhotos/main/'),
        ),
    ]
